#include <iostream>
#include <fstream>
#include <sstream>
#include <unordered_map>
#include <unordered_set>
#include <string>
#include <regex>
#include <windows.h>
#include <algorithm>
#include <cctype>